server:
    port: 8080

#spring:
#    datasource:
#        url: ${SPRING_DATASOURCE_URL}
#        username: ${SPRING_DATASOURCE_USERNAME}
#        password: ${SPRING_DATASOURCE_PASSWORD}

spring:
    jpa:
        hibernate:
            ddl-auto: none

logging:
    level:
        root: INFO
        org:
            hibernate: DEBUG
            springframework:
                web: DEBUG
