server:
    port: 8080

#spring:
#    datasource:
#        url: ${SPRING_DATASOURCE_URL}
#        username: ${SPRING_DATASOURCE_USERNAME}
#        password: ${SPRING_DATASOURCE_PASSWORD}

spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none

liquibase:
    change-log: classpath:/db/change-log.sql
    url: ${SPRING_DATASOURCE_URL}


logging:
    level:
        root: INFO
#        org:
#            hibernate: DEBUG
#            springframework:
#                web: DEBUG
