CREATE TABLE IF NOT EXISTS SCHEMA_STUDENT (
  sid SERIAL NOT NULL,
  name VARCHAR(64) NOT NULL,
  age INTEGER DEFAULT 25,
  PRIMARY KEY (sid)
);

INSERT INTO SCHEMA_STUDENT
  (name, age)
VALUES
  ('schema_ming', 23);

